name: Create Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v*
      - auto_build*
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    tags:
      - v*
      - auto_build*
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (test/release)'
        required: true
        default: 'test'

jobs:
  test-build:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup

      - name: Build Chrome (Test Build)
        run: |
          yarn build:chrome:mv3:dev

      - name: Get Version Name for Test Build
        id: get-test-version
        run: echo "version=test-$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Rename Test Build Files
        run: |
          mkdir -p dist/renamed
          find dist -name "*.zip" -exec bash -c 'FILENAME=$(basename {}); EXT="${FILENAME##*.}"; NAME="${FILENAME%.*}"; mv {} dist/renamed/$NAME-${{ steps.get-test-version.outputs.version }}.$EXT' \;

      - name: Create Test Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test-${{ steps.get-test-version.outputs.version }}
          name: Test Build ${{ steps.get-test-version.outputs.version }}
          files: dist/renamed/*.zip
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-build:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.build_type == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup

      - name: Build Chrome (Release Build)
        run: |
          yarn build:chrome:mv3

      - name: Get Version Name
        uses: actions/github-script@v6
        id: get-version
        with:
          script: |
            const str=process.env.GITHUB_REF;
            return str.substring(str.indexOf("v"));
          result-encoding: string

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/unisat-chrome-mv3-${{steps.get-version.outputs.result}}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
