name: Create Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v*
      - auto_build*
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    tags:
      - v*
      - auto_build*
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (test/release)'
        required: true
        default: 'test'

jobs:
  test-build:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'test'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install dependencies
        run: |
          # 正常安装依赖
          yarn install --ignore-scripts

          # 手动为unisat-wallet-sdk安装缺少的bitcoinjs-lib
          if [ -d "node_modules/@unisat/wallet-sdk" ]; then
            echo "Installing bitcoinjs-lib for @unisat/wallet-sdk"
            cd node_modules/@unisat/wallet-sdk
            mkdir -p node_modules
            cd ../..
            if [ -d "bitcoinjs-lib" ]; then
              # 如果主项目已安装了这个库，直接复制
              cp -r bitcoinjs-lib @unisat/wallet-sdk/node_modules/
            else
              # 否则单独安装
              cd @unisat/wallet-sdk
              yarn add bitcoinjs-lib@6.1.6 --no-lockfile
              cd ../..
            fi

            # 应用补丁
            cd @unisat/wallet-sdk
            if [ -d "patches" ]; then
              npx patch-package --error-on-fail=false
            fi
            cd ../..
            cd ..
          fi

          # 应用主项目补丁
          if [ -d "patches" ]; then
            npx patch-package --error-on-fail=false
          fi

      - name: Build Chrome (Test Build)
        run: yarn build:chrome:mv3

      - name: Get Version Name for Test Build
        id: get-test-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          TIMESTAMP=$(date +'%Y%m%d%H%M')
          echo "version=v$VERSION-test-$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "Using test version: v$VERSION-test-$TIMESTAMP"

      - name: Prepare Test Release Files
        run: |
          mkdir -p dist/release
          find dist -name "*.zip" -exec cp {} dist/release/unisat-chrome-mv3-${{ steps.get-test-version.outputs.version }}.zip \;
          ls -la dist/release/

      - name: Create Test Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get-test-version.outputs.version }}
          name: Test Build ${{ steps.get-test-version.outputs.version }}
          files: dist/release/*.zip
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-build:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.build_type == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install dependencies
        run: |
          # 正常安装依赖
          yarn install --ignore-scripts

          # 手动为unisat-wallet-sdk安装缺少的bitcoinjs-lib
          if [ -d "node_modules/@unisat/wallet-sdk" ]; then
            echo "Installing bitcoinjs-lib for @unisat/wallet-sdk"
            cd node_modules/@unisat/wallet-sdk
            mkdir -p node_modules
            cd ../..
            if [ -d "bitcoinjs-lib" ]; then
              # 如果主项目已安装了这个库，直接复制
              cp -r bitcoinjs-lib @unisat/wallet-sdk/node_modules/
            else
              # 否则单独安装
              cd @unisat/wallet-sdk
              yarn add bitcoinjs-lib@6.1.6 --no-lockfile
              cd ../..
            fi

            # 应用补丁
            cd @unisat/wallet-sdk
            if [ -d "patches" ]; then
              npx patch-package --error-on-fail=false
            fi
            cd ../..
            cd ..
          fi

          # 应用主项目补丁
          if [ -d "patches" ]; then
            npx patch-package --error-on-fail=false
          fi

      - name: Build Chrome (Release Build)
        run: yarn build:chrome:mv3

      - name: Get Version Name
        id: get-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: v$VERSION"

      - name: Prepare Release Files
        run: |
          mkdir -p dist/release
          find dist -name "*.zip" -exec cp {} dist/release/unisat-chrome-mv3-${{ steps.get-version.outputs.version }}.zip \;
          ls -la dist/release/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/release/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
